name: Pipeline 2

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: ls -a ;cd not_again; ls -a;cd full-stack-open-pokedex; ls -a; npm install
      - name: Check style
        run: cd not_again;cd full-stack-open-pokedex; npm run eslint
